services:
  gate:
    image: ghcr.io/creatorsgarten/garden-gate
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/.data
      - ./ota-updater/data:/app/.ota
    restart: unless-stopped
    ports:
      - 3000:3000
