services:
  gate:
    image: ghcr.io/creatorsgarten/garden-gate
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/.data
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
